version: "3.9"
services:
  supabase:
    image: supabase/postgres:15.3.0
    container_name: supabase
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shelf
      POSTGRES_USER: postgres
    ports:
      - "54321:5432" # Supabase Postgres port
    volumes:
      - supabase-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - supabase
    ports:
      - "8080:8080"
    environment:
      SUPABASE_URL: http://supabase:54321
      SUPABASE_KEY: secret-api-key
      DATABASE_URL: postgres://postgres:postgres@supabase:5432/shelf
    volumes:
      - .:/src
    command: [ "/src/start.sh" ]

volumes:
  supabase-data:
