version: "3.9"
services:
  supabase:
    image: supabase/postgres:latest
    container_name: supabase
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shelf
      POSTGRES_USER: postgres
    ports:
      - "54321:5432"
    volumes:
      - supabase-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - supabase
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/src
    command: [ "/src/init.sh" ]

volumes:
  supabase-data:
